-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 14:08:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`developers` (
  `developer_id` INT(11) NOT NULL,
  `developer_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`developer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genre_id` INT(11) NOT NULL,
  `genre_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `game_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `release_date` DATE NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `developers_developer_id` INT(11) NULL DEFAULT NULL,
  `age_rating` VARCHAR(45) NULL DEFAULT NULL,
  `genres_genre_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_games_developer1_idx` (`developers_developer_id` ASC),
  INDEX `fk_games_genre1_idx` (`genres_genre_id` ASC),
  CONSTRAINT `fk_games_developer1`
    FOREIGN KEY (`developers_developer_id`)
    REFERENCES `mydb`.`developers` (`developer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_genre1`
    FOREIGN KEY (`genres_genre_id`)
    REFERENCES `mydb`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`platforms` (
  `platform_id` INT(11) NOT NULL,
  `platform_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`platform_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`games_platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_platforms` (
  `platforms_platform_id` INT(11) NOT NULL,
  `games_game_id` INT(11) NOT NULL,
  PRIMARY KEY (`platforms_platform_id`, `games_game_id`),
  INDEX `fk_platforms_has_games_games1_idx` (`games_game_id` ASC),
  INDEX `fk_platforms_has_games_platforms1_idx` (`platforms_platform_id` ASC),
  CONSTRAINT `fk_platforms_has_games_games1`
    FOREIGN KEY (`games_game_id`)
    REFERENCES `mydb`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_platforms_has_games_platforms1`
    FOREIGN KEY (`platforms_platform_id`)
    REFERENCES `mydb`.`platforms` (`platform_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`games_in_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_in_stock` (
  `games_in_stock_id` INT(11) NOT NULL,
  `games_platforms_platforms_platform_id` INT(11) NULL DEFAULT NULL,
  `games_platforms_games_game_id` INT(11) NULL DEFAULT NULL,
  `isReserved` TINYINT(4) NOT NULL,
  PRIMARY KEY (`games_in_stock_id`),
  INDEX `fk_games_in_stock_platforms_has_games1_idx` (`games_platforms_platforms_platform_id` ASC, `games_platforms_games_game_id` ASC),
  CONSTRAINT `fk_games_in_stock_platforms_has_games1`
    FOREIGN KEY (`games_platforms_platforms_platform_id` , `games_platforms_games_game_id`)
    REFERENCES `mydb`.`games_platforms` (`platforms_platform_id` , `games_game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`games_complete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_complete` (`game_id` INT, `title` INT, `release_date` INT, `description` INT, `image_url` INT, `age_rating` INT, `developer_name` INT, `genre_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`games_platforms_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_platforms_view` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`games_complete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games_complete`;
USE `mydb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mydb`.`games_complete` AS select `j`.`game_id` AS `game_id`,`j`.`title` AS `title`,`j`.`release_date` AS `release_date`,`j`.`description` AS `description`,`j`.`image_url` AS `image_url`,`j`.`age_rating` AS `age_rating`,`j`.`developer_name` AS `developer_name`,`gen`.`genre_name` AS `genre_name` from (((select `g`.`game_id` AS `game_id`,`g`.`title` AS `title`,`g`.`release_date` AS `release_date`,`g`.`description` AS `description`,`g`.`image_url` AS `image_url`,`g`.`age_rating` AS `age_rating`,`g`.`genres_genre_id` AS `genres_genre_id`,`d`.`developer_name` AS `developer_name` from (`mydb`.`games` `g` join `mydb`.`developers` `d`) where (`g`.`developers_developer_id` = `d`.`developer_id`))) `j` join `mydb`.`genres` `gen`) where (`j`.`genres_genre_id` = `gen`.`genre_id`);

-- -----------------------------------------------------
-- View `mydb`.`games_platforms_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games_platforms_view`;
USE `mydb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mydb`.`games_platforms_view` AS (select `t`.`games_game_id` AS `games_game_id`,`t`.`title` AS `title`,`t`.`release_date` AS `release_date`,`p`.`platform_name` AS `platform_name` from (((select `gp`.`games_game_id` AS `games_game_id`,`g`.`title` AS `title`,`g`.`release_date` AS `release_date`,`gp`.`platforms_platform_id` AS `platforms_platform_id` from (`mydb`.`games_platforms` `gp` join `mydb`.`games` `g`) where (`gp`.`games_game_id` = `g`.`game_id`))) `t` join `mydb`.`platforms` `p`) where (`t`.`platforms_platform_id` = `p`.`platform_id`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
